# http://docs.ansible.com/ansible/latest/playbooks_best_practices.html#directory-layout
---
# playbook.yml

- hosts: all
  gather_facts: yes
  become: true
  become_user: "root"
  vars_files:
    - "vars.yml"
  roles:
    - geerlingguy.firewall
    - geerlingguy.git
    - apolloclark.nano_highlighting
    - apolloclark.aws_cli
    - geerlingguy.docker
    - geerlingguy.kubernetes
