# http://docs.ansible.com/ansible/latest/playbooks_variables.html#variable-file-separation
---
hostname: all

# geerlingguy/ntp
ntp_timezone: America/New_York

# geerlingguy/firewall
firewall_allowed_tcp_ports:
  - "22"
  - "25"

# apolloclark/aws-cli
awscli:
  pip_user: 
    - root

# rvm.ruby
rvm1_bundler_install: True
rvm1_user: "root"
rvm1_rvm_version: "stable"
rvm1_install_path: /usr/local/rvm

# geerlingguy.ruby
ruby_install_gems:
  - serverspec
ruby_install_gems_user: "root"

# geerlingguy.docker
docker_edition: 'ce'
docker_version: '17.03.3~ce-0~ubuntu-xenial'
docker_package: "docker-{{ docker_edition }}={{ docker_version }}"

# geerlingguy.kubernetes
# kuberenetes_debug: True
kubernetes_role: master
kubernetes_allow_pods_on_master: True
kubernetes_kubelet_extra_args: "--fail-swap-on=false"
